# Generated by Django 4.2.5 on 2023-09-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='name')),
                ('ish_joyi', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('birthday', models.DateField()),
                ('info', models.TextField()),
            ],
        ),
    ]
